// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvZBkd47zoGwog31wac4bsQYfFlBZ9nOM',
    appId: '1:942967095269:web:9d35eeb86eb4781bc5b90c',
    messagingSenderId: '942967095269',
    projectId: 'workoutapp-11e2a',
    authDomain: 'workoutapp-11e2a.firebaseapp.com',
    storageBucket: 'workoutapp-11e2a.firebasestorage.app',
    measurementId: 'G-FRHGKBNQGW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBefe21bFyqUTw0RtBfhwWWxaRZ9ehrrds',
    appId: '1:942967095269:android:017b7f298baf9f46c5b90c',
    messagingSenderId: '942967095269',
    projectId: 'workoutapp-11e2a',
    storageBucket: 'workoutapp-11e2a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbbYkYo_L_ULeraOLFSEgLPv7YPBOqUz8',
    appId: '1:942967095269:ios:295fba1903bb57d0c5b90c',
    messagingSenderId: '942967095269',
    projectId: 'workoutapp-11e2a',
    storageBucket: 'workoutapp-11e2a.firebasestorage.app',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbbYkYo_L_ULeraOLFSEgLPv7YPBOqUz8',
    appId: '1:942967095269:ios:295fba1903bb57d0c5b90c',
    messagingSenderId: '942967095269',
    projectId: 'workoutapp-11e2a',
    storageBucket: 'workoutapp-11e2a.firebasestorage.app',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCvZBkd47zoGwog31wac4bsQYfFlBZ9nOM',
    appId: '1:942967095269:web:9d35eeb86eb4781bc5b90c',
    messagingSenderId: '942967095269',
    projectId: 'workoutapp-11e2a',
    authDomain: 'workoutapp-11e2a.firebaseapp.com',
    storageBucket: 'workoutapp-11e2a.firebasestorage.app',
    measurementId: 'G-FRHGKBNQGW',
  );
}
